# Version 2019.02.18-13-16
version: '3'

services:
  mcpe:
    image: registry.cn-shanghai.aliyuncs.com/infinites/mcpe:2019.02.18-13-16
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    volumes:
      - .:/app:rw
