# Version 2019.02.18-13-16
version: '3'

services:
  mcpc:
    image: registry.cn-shanghai.aliyuncs.com/infinites/mcpc
    container_name: mcpc
    ports:
      - "25565:25565"
    volumes:
      - .:/app:rw
